/*
 * Sean Luo 17/05/2018
 * CD Collection.java
 * This progrem calculates the CD Collection
 */
package wordgame2;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Random;

/**
 *
 * @author toluo7449
 */
public class WordGame2 extends javax.swing.JFrame {

    ArrayList <String> names = new ArrayList();
    ArrayList <String> verbs = new ArrayList();
    ArrayList <String> adverbs = new ArrayList();
    ArrayList <String> nouns = new ArrayList();
    ArrayList <String> adjectives = new ArrayList();
    Random rn = new Random();

    public WordGame2() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        adverb = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        noun = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        adjective = new javax.swing.JTextField();
        DisplayButton = new javax.swing.JButton();
        AddWordsButton = new javax.swing.JButton();
        RemoveWordsButton = new javax.swing.JButton();
        InitializeButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        outputBox = new javax.swing.JTextArea();
        verb = new javax.swing.JTextField();

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("The Word Game2");

        jLabel2.setText("Enter a Name");

        jLabel3.setText("Enter a verb");

        jLabel4.setText("Enter a adverb");

        jLabel5.setText("Enter a noun");

        jLabel6.setText("Enter a adjective");

        DisplayButton.setText("Display");
        DisplayButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DisplayButtonActionPerformed(evt);
            }
        });

        AddWordsButton.setText("Add Words");
        AddWordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddWordsButtonActionPerformed(evt);
            }
        });

        RemoveWordsButton.setText("Remove words");
        RemoveWordsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveWordsButtonActionPerformed(evt);
            }
        });

        InitializeButton.setText("Initialize");
        InitializeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InitializeButtonActionPerformed(evt);
            }
        });

        outputBox.setColumns(20);
        outputBox.setRows(5);
        jScrollPane1.setViewportView(outputBox);

        verb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                verbActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel6))
                                .addGap(104, 104, 104)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(Name, javax.swing.GroupLayout.DEFAULT_SIZE, 72, Short.MAX_VALUE)
                                    .addComponent(adverb)
                                    .addComponent(noun)
                                    .addComponent(adjective)
                                    .addComponent(verb)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(DisplayButton)
                                        .addGap(29, 29, 29)
                                        .addComponent(AddWordsButton))
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addComponent(RemoveWordsButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(InitializeButton)))
                        .addGap(0, 47, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(verb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(adverb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(DisplayButton)
                            .addComponent(AddWordsButton)
                            .addComponent(RemoveWordsButton)
                            .addComponent(InitializeButton)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(noun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(adjective, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 138, Short.MAX_VALUE)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void DisplayButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DisplayButtonActionPerformed
         outputBox.setText( names.get(rn.nextInt(names.size()))
      + " " + adverbs.get(rn.nextInt(names.size()))
      + " " + verbs.get(rn.nextInt(names.size()))
      + " on top of the "  + adjectives.get(rn.nextInt(names.size()))
      + " " + nouns.get(rn.nextInt(names.size()))
      + " trying to escape the " + adjectives.get(rn.nextInt(names.size()))
      + " " + nouns.get(rn.nextInt(names.size())) + "!");
    }//GEN-LAST:event_DisplayButtonActionPerformed

    private void RemoveWordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveWordsButtonActionPerformed
       //Remove the last element from the end of each of the Arrays.
        removeNames();
        removeverbs();
        removeadverbs();
        removenouns();
        removeadjectives();

    }//GEN-LAST:event_RemoveWordsButtonActionPerformed

    private void removeNames(){
        names.remove(names.size()-1);
    }
    private void removeverbs(){
        verbs.remove(verbs.size()-1);
    }
    private void removeadverbs(){
        adverbs.remove(adverbs.size()-1);
    }
    private void removenouns(){
        nouns.remove(nouns.size()-1);
    }
    private void removeadjectives(){
        adjectives.remove(adjectives.size()-1);
    }
    private void InitializeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InitializeButtonActionPerformed
        Collections.addAll(names, "Rudolph", "Santa");
        Collections.addAll(verbs, "flew", "crashed");
        Collections.addAll(adverbs, "quickly", "slowly");
        Collections.addAll(nouns, "mountain", "snowman");
        Collections.addAll(adjectives, "huge", "abominable");
        InitializeButton.setEnabled(false);
    }//GEN-LAST:event_InitializeButtonActionPerformed

    private void AddWordsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddWordsButtonActionPerformed
        names.add(Name.getText());
        verbs.add(verb.getText());
        adverbs.add(adverb.getText());
        nouns.add(noun.getText());
        adjectives.add(adjective.getText());
    }//GEN-LAST:event_AddWordsButtonActionPerformed

    private void verbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_verbActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_verbActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WordGame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WordGame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WordGame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WordGame2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WordGame2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddWordsButton;
    private javax.swing.JButton DisplayButton;
    private javax.swing.JButton InitializeButton;
    private javax.swing.JTextField Name;
    private javax.swing.JButton RemoveWordsButton;
    private javax.swing.JTextField adjective;
    private javax.swing.JTextField adverb;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField noun;
    private javax.swing.JTextArea outputBox;
    private javax.swing.JTextField verb;
    // End of variables declaration//GEN-END:variables

}

